name: Test
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn --prefer-offline

  lint:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Run Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Run Test
        run: yarn test
        env:
          SECRET_NAME: ${{ secrets.SECRET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_DEFAULT_OUTPUT: ${{ secrets.AWS_DEFAULT_OUTPUT }}

  test-github-actions:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Package
        run: yarn package

      - name: Use AWS Secrets Manager Actions from current branch
        uses: ./
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: ${{ secrets.SECRET_NAME }}

      - name: Should have SCIENTIFIC_NAME
        uses: therussiankid92/gat@v1.5
        with:
          assertion: should.equal
          expected: Pygoscelis adeliae
          actual: ${{ env.SCIENTIFIC_NAME }}
